# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blosm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumreleasedate',
            field=models.DateField(),
        ),
    ]
