# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blosm_app', '0002_auto_20171004_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumreleasedate',
            field=models.DateTimeField(),
        ),
    ]
