# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blosm_app', '0004_auto_20171004_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumgenre',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
